// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewgwpmafszgwslsbvmej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Z3dwbWFmc3pnd3Nsc2J2bWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NDQ5NTYsImV4cCI6MjA1MTUyMDk1Nn0.ddrN3t4QKEZNm6bf0-ntFHczgkjCAVP_5SjTLRo_aRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);